### PR TITLE
Add process exit to gulp done callback

### LINKED ISSUE #31: handle a mocha bug that doesn't exit the process on successful test run
Per this upstream issue in `gulp-mocha` https://github.com/sindresorhus/gulp-mocha/issues/54, the pipeline will not exit on success.

This is something that our pipeline should try and handle if possible.

### PR DESCRIPTION
**Pull request by bsawyer**
fixes #31

### CODE REVIEW

**Comment by obuckley-kenzan** [comment]
Can one of the admins verify this patch?

**Comment by obuckley-kenzan** [comment]
@bsawyer 
I think I would prefer fixtures go in the _test_ folder.  Thoughts?

@paul-barry-kenzan 
Please review.

**Comment by paul-barry-kenzan** [comment]
@bsawyer @obuckley-kenzan 
I looked at the gulp-mocha error mentioned in #31, and the work here looks good to me. 

As for as the fixtures, I lean towards having them tucked in the `/test` directory.

**Comment by bsawyer** [comment]
Whoops, good catch. Why are they not in test?...

**Comment by obuckley-kenzan** [comment]
ok to test

**Comment by bsawyer** [comment]
moved fixtures @obuckley-kenzan @paul-barry-kenzan

**Pull request merged**
