### PR TITLE
Fix #15: Pass user options to writeReports method

### LINKED ISSUE #15: Pass user provided options to the reporting method
Currently, `istanbul.writeReports` is called without any options, however, the user should be able to pass options to override the defaults.

### PR DESCRIPTION
**Pull request by paul-barry-kenzan**

### CODE REVIEW

**Comment by obuckley-kenzan** [comment]
@paul-barry-kenzan 
Should we add this to the README.md?

**Comment by paul-barry-kenzan** [comment]
@obuckley-kenzan 
Updated the README with config options

**Comment by obuckley-kenzan** [comment]
@paul-barry-kenzan do you need a release ?

**Comment by obuckley-kenzan** [comment]
fixes #15

**Comment by paul-barry-kenzan** [comment]
@obuckley-kenzan 
Not necessary for my current work since coverage has been disabled for my project.

**Pull request merged**
