### PR TITLE
Bump validate js version

### PR DESCRIPTION
**Pull request by mrgardner**

### CODE REVIEW

**Comment by obuckley-kenzan** [comment]
looks like a linting failure @mrgardner

**Comment by obuckley-kenzan** [comment]
@mrgardner 
Another linting failure.  Please considering running `gulp build` prior to pushing your changes

**Comment by mrgardner** [comment]
@obuckley-kenzan this is another linting error that shouldn't be happening.  For some reason it is getting an older version of the eslint file because the max-nested-callbacks is 4.  Where on the master branch on Validate-js the max-nested-callbacks is 8.

**Comment by obuckley-kenzan** [comment]
@mrgardner 
Reviewing the docs, it looks like the property should be `max`.  Can you try that and see if we need to make a quick fix to the `eslintrc` file?

**Comment by obuckley-kenzan** [comment]
hmm, actually, looking at the workspace for the build, the file shows 4, not 8
https://kenzan.ci.cloudbees.com/job/CI-pipeline-test-node/ws/node_modules/pipeline-validate-js/.eslintrc/*view*/

**Comment by mrgardner** [comment]
Which is strange because on validate js it is set to 8 https://github.com/kenzanlabs/pipeline-validate-js/blob/master/.eslintrc#L108

**Comment by obuckley-kenzan** [comment]
@mrgardner 
Please try 1.0.0-rc4 
```
$ npm publish --tags
+ pipeline-validate-js@1.0.0-rc4
```

**Comment by mrgardner** [comment]
@obuckley-kenzan 
That did the trick.  It is working normally now.

**Comment by obuckley-kenzan** [comment]
@mrgardner 
This one was definitely on me.  I didn't pull your latest changes which is why master looks correct.  It was a bad tag on my part.

**Pull request merged**
